import os
env = SConscript('godot-cpp/SConstruct')

env.Append(CPPPATH="src/")

#env.Append(LIBPATH="lib")
#env.Append(LIB="libcurl-x64.dll")

libcurl_dll = 'lib/curl/libcurl.dll'
opencv_dll = 'lib/opencv/opencv_world480.dll'
imgHash_dll = 'lib/opencv/opencv_img_hash480.dll'
dlls = ['lib/curl/libcurl.dll', 'lib/opencv/opencv_world480d.dll']

libcurl_lib_dir = 'lib/curl'
opencv_lib_dir = 'lib/opencv'

env.Append(LIBPATH=[libcurl_lib_dir, opencv_lib_dir])

env.Append(LIBS=['curl', 'opencv_world480', 'opencv_img_hash480'])

env.Append(LIBS=[
    'Normaliz.lib',
    'Ws2_32',   # Windows Sockets API
    'Wldap32',  # Windows LDAP client API
    'Crypt32',  # Windows Cryptography API
    'advapi32', # Advanced Windows API
])

env.Append(LINKFLAGS=['/SUBSYSTEM:CONSOLE'])

src = Glob("src/*.cpp")

def copy_dll(target, source, env):
    for t in target:
        env.Install(os.path.dirname(t.abspath), libcurl_dll)
        env.Install(os.path.dirname(t.abspath), opencv_dll)
        env.Install(os.path.dirname(t.abspath), imgHash_dll)

if env['platform'] == 'linux':
    pass
elif env['platform'] == 'windows':
    libpath = '../libtest{}{}'.format(env['suffix'], env['SHLIBSUFFIX'])
    sharedLib = env.SharedLibrary(libpath, src)
    env.AddPostAction(sharedLib, copy_dll)
    Default(sharedLib)
elif env['platform'] == 'android':
    pass